### ISSUE TITLE
`ProcessEndpoint` is an unknown class in Pharo 10

### ISSUE THREAD

**Issue by capsulecorplab** [pavel-krivanek/terminal#3]
![Screenshot from 2022-09-26 22-12-30](https://user-images.githubusercontent.com/14095576/192430292-a22dd48f-4ea0-4a78-afd8-5a8d945653ca.png)

**Comment by pavel-krivanek** [comment]
As mentioned in readme, this project is obsolete and not supported for newer Pharo versions, it was replaced by https://github.com/lxsang/PTerm/
